apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
  name: demo
  namespace: default
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - env:
            - name: OTEL_SERVICE_NAME
              value: demo
            - name: OTEL_LOG_LEVEL
              value: warn
            - name: OTEL_TRACES_SAMPLER
              value: "traceidratio"
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "0.1"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: 'http://opentelemetry-demo-jaeger-collector:4318'
          image: registry.cn-hangzhou.aliyuncs.com/private-mesh/hellob:demo
          imagePullPolicy: Always
          name: demo
          resources:
            limits:
              cpu: '2'
              memory: 4048Mi
            requests:
              cpu: '2'
              memory: 4048Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo
  name: demo
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: demo
  sessionAffinity: None
  type: LoadBalancer
