//go:build ignore

// This file is generated by alibaba-otel tool, DO NOT EDIT MANUALLY
package main

import (
	"github.com/alibaba/opentelemetry-go-auto-instrumentation/pkg" // use otel setup
	_ "go.opentelemetry.io/otel"                                   // depends on otel
	_ "go.opentelemetry.io/otel/baggage"                           // depends on otel
	_ "go.opentelemetry.io/otel/sdk/trace"                         // depends on otel
	"log"                                                          // for log.Printf
	"runtime/debug"                                                // for debug.Stack
	_ "unsafe"                                                     // for go:linkname when declaring printstack/getstack variable
)
